FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

EXPOSE 24678

ENV NODE_ENV=development

ENV HOST=0.0.0.0

ENV NODE_OPTIONS=--max-old-space-size=4096

# CMD ["npm", "run", "dev"]

