FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat bash git python3 wget tar make


# Python and mma install
ARG MMA_VERSION=25.05.0
RUN wget https://www.mellowood.ca/mma/mma-bin-25.05.0.tar.gz && \
    mkdir -p /opt/mma && \
    tar -xzvf mma-bin-25.05.0.tar.gz -C /opt/mma --strip-components=1 && \
    rm mma-bin-25.05.0.tar.gz && \
    cd /opt/mma && python3 mma.py -G

# music21 install
RUN apk add --no-cache python3-dev py3-pip
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir music21

COPY package.json pnpm-lock.yaml ./


RUN npm install -g pnpm


RUN pnpm install --frozen-lockfile


COPY . .

RUN pnpm prisma generate

EXPOSE 3000

ENV HOST=0.0.0.0
RUN pnpm build

