export const availableLanguages = ["french", "english", "spanish", "german", "chinese_simplified"] as const;

export const languagePack = {
  homepageDefaultTitle: {
    french: "Bienvenue sur MusicSandbox !",
    english: "Welcome to MusicSandbox!",
    spanish: "¡Bienvenido a MusicSandbox!",
    german: "Willkommen bei MusicSandbox!",
    chinese_simplified: "欢迎来到 MusicSandbox！",
  },
  homepageSessionTitle: {
    french: "Bon retour parmi nous",
    english: "Welcome back",
    spanish: "Bienvenido de nuevo",
    german: "Willkommen zurück",
    chinese_simplified: "欢迎回来",
  },
  homepage: {
    french: "Page d'Accueil",
    english: "Home Page",
    spanish: "Página de Inicio",
    german: "Startseite",
    chinese_simplified: "主页",
  },
  dashboard: {
    french: "Tableau de bord",
    english: "Dashboard",
    spanish: "Panel de control",
    german: "Dashboard",
    chinese_simplified: "仪表板",
  },
  explorePageTitle: {
    french: "Explorer",
    english: "Explore",
    spanish: "Explorar",
    german: "Entdecken",
    chinese_simplified: "浏览",
  },
  favoritesPageTitle: {
    french: "Favoris",
    english: "Favorites",
    spanish: "Favoritos",
    german: "Favoriten",
    chinese_simplified: "收藏",
  },
  dashboardPageTitle: {
    french: "Vos playlists",
    english: "Your playlists",
    spanish: "Tus listas",
    german: "Deine Playlists",
    chinese_simplified: "您的播放列表",
  },
  recentlyPlayed: {
    french: "Joués récemment",
    english: "Recently played",
    spanish: "Recientes",
    german: "Zuletzt gespielt",
    chinese_simplified: "最近播放",
  },
  moreOfThem: {
    french: "Vous les avez aimé",
    english: "You liked them",
    spanish: "Te gustaron",
    german: "Dir haben sie gefallen",
    chinese_simplified: "你喜欢的",
  },
  popularExercices: {
    french: "Exercices populaires",
    english: "Popular exercises",
    spanish: "Ejercicios populares",
    german: "Beliebte Übungen",
    chinese_simplified: "热门练习",
  },
  discover: {
    french: "Découvrir",
    english: "Discover",
    spanish: "Descubrir",
    german: "Entdecken",
    chinese_simplified: "发现",
  },
  accounts: {
    french: "Utilisateurs",
    english: "Users",
    spanish: "Usuarios",
    german: "Benutzer",
    chinese_simplified: "用户",
  },
  playlists: {
    french: "Playlists",
    english: "Playlists",
    spanish: "Listas",
    german: "Playlists",
    chinese_simplified: "播放列表",
  },
  general: {
    french: "Général",
    english: "General",
    spanish: "General",
    german: "Allgemein",
    chinese_simplified: "常规",
  },
  backing_track: {
    french: "Accompagnement",
    english: "Backing track",
    spanish: "Acompañamiento",
    german: "Begleitung",
    chinese_simplified: "伴奏",
  },
  appearance: {
    french: "Apparence",
    english: "Appearance",
    spanish: "Apariencia",
    german: "Aussehen",
    chinese_simplified: "外观",
  },
  midi: {
    french: "MIDI",
    english: "MIDI",
    spanish: "MIDI",
    german: "MIDI",
    chinese_simplified: "MIDI",
  },
  seeAll: {
    french: "voir tout",
    english: "see all",
    spanish: "ver todo",
    german: "alle anzeigen",
    chinese_simplified: "查看全部",
  },
  profile: {
    french: "Profil",
    english: "Profile",
    spanish: "Perfil",
    german: "Profil",
    chinese_simplified: "个人资料",
  },
  settings: {
    french: "Paramètres",
    english: "Settings",
    spanish: "Ajustes",
    german: "Einstellungen",
    chinese_simplified: "设置",
  },
  theme: {
    french: "Thème",
    english: "Theme",
    spanish: "Tema",
    german: "Theme",
    chinese_simplified: "主题",
  },
  language: {
    french: "Langue",
    english: "Language",
    spanish: "Idioma",
    german: "Sprache",
    chinese_simplified: "语言",
  },
  log_out: {
    french: "Déconnexion",
    english: "Log out",
    spanish: "Cerrar sesión",
    german: "Abmelden",
    chinese_simplified: "登出",
  },
  overview: {
    french: "Aperçu",
    english: "Overview",
    spanish: "Resumen",
    german: "Übersicht",
    chinese_simplified: "概览",
  },
  liked: {
    french: "Aimés",
    english: "Liked",
    spanish: "Me gusta",
    german: "Gefällt mir",
    chinese_simplified: "喜欢",
  },
  users: {
    french: "Utilisateurs",
    english: "Users",
    spanish: "Usuarios",
    german: "Benutzer",
    chinese_simplified: "用户",
  },
  user: {
    french: "Utilisateur",
    english: "User",
    spanish: "Usuario",
    german: "Benutzer",
    chinese_simplified: "用户",
  },
  bpm: {
    french: "BPM",
    english: "BPM",
    spanish: "BPM",
    german: "BPM",
    chinese_simplified: "BPM",
  },
  pop: {
    french: "Pop.", // popularité
    english: "Pop.",
    spanish: "Pop.",
    german: "Pop.",
    chinese_simplified: "热度",
  },
  all: {
    french: "Tous",
    english: "All",
    spanish: "Todos",
    german: "Alle",
    chinese_simplified: "全部",
  },
  browse_exercices: {
    french: "Parcourir les exercices",
    english: "Browse exercises",
    spanish: "Explorar ejercicios",
    german: "Übungen durchsuchen",
    chinese_simplified: "浏览练习",
  },
  search_in_playlist: {
    french: "Chercher dans la playlist",
    english: "Search in playlist",
    spanish: "Buscar en la lista",
    german: "In Playlist suchen",
    chinese_simplified: "在播放列表中搜索",
  },
  piano_roll: {
    french: "Piano",
    english: "Piano",
    spanish: "Piano",
    german: "Klavier",
    chinese_simplified: "钢琴",
  },
  chords: {
    french: "Accords",
    english: "Chords",
    spanish: "Acordes",
    german: "Akkorde",
    chinese_simplified: "和弦",
  },
  sheet: {
    french: "Partition",
    english: "Sheet",
    spanish: "Partitura",
    german: "Notenblatt",
    chinese_simplified: "乐谱",
  },
  guitar: {
    french: "Guitare",
    english: "Guitar",
    spanish: "Guitarra",
    german: "Gitarre",
    chinese_simplified: "吉他",
  },
  save_settings: {
    french: "Enregistrer les paramètres",
    english: "Save settings",
    spanish: "Guardar ajustes",
    german: "Einstellungen speichern",
    chinese_simplified: "保存设置",
  },
  default: {
    french: "Défaut",
    english: "Default",
    spanish: "Predeterminado",
    german: "Standard",
    chinese_simplified: "默认",
  },
  presets: {
    french: "préréglages",
    english: "presets",
    spanish: "ajustes previos",
    german: "Voreinstellungen",
    chinese_simplified: "预设",
  },
  count_before_play: {
    french: "Décompte",
    english: "Count-in",
    spanish: "Cuenta atrás",
    german: "Einzählen",
    chinese_simplified: "预拍",
  },
  transpose: {
    french: "Transposition",
    english: "Transpose",
    spanish: "Transposición",
    german: "Transponieren",
    chinese_simplified: "移调",
  },
  practice: {
    french: "Pratique",
    english: "Practice",
    spanish: "Práctica",
    german: "Üben",
    chinese_simplified: "练习",
  },
  repeats: {
    french: "Répétitions",
    english: "Repeats",
    spanish: "Repeticiones",
    german: "Wiederholungen",
    chinese_simplified: "重复",
  },
  bpm_practice: {
    french: "Pratique BPM",
    english: "BPM practice",
    spanish: "Práctica BPM",
    german: "BPM-Übung",
    chinese_simplified: "BPM 练习",
  },
  active: {
    french: "Activé",
    english: "Active",
    spanish: "Activado",
    german: "Aktiviert",
    chinese_simplified: "已激活",
  },
  melody: {
    french: "Mélodie",
    english: "Melody",
    spanish: "Melodía",
    german: "Melodie",
    chinese_simplified: "旋律",
  },
  piano: {
    french: "Piano",
    english: "Piano",
    spanish: "Piano",
    german: "Klavier",
    chinese_simplified: "钢琴",
  },
  bass: {
    french: "Basse",
    english: "Bass",
    spanish: "Bajo",
    german: "Bass",
    chinese_simplified: "贝斯",
  },
  drums: {
    french: "Batterie",
    english: "Drums",
    spanish: "Batería",
    german: "Schlagzeug",
    chinese_simplified: "鼓",
  },
  style: {
    french: "Style",
    english: "Style",
    spanish: "Estilo",
    german: "Stil",
    chinese_simplified: "风格",
  },
  show_chords: {
    french: "Afficher les accords",
    english: "Show chords",
    spanish: "Mostrar acordes",
    german: "Akkorde anzeigen",
    chinese_simplified: "显示和弦",
  },
  highlight_current_measure: {
    french: "Souligner la mesure actuelle",
    english: "Highlight current measure",
    spanish: "Resaltar compás actual",
    german: "Aktuellen Takt markieren",
    chinese_simplified: "突出显示当前小节",
  },
  chords_diagrams: {
    french: "Diagrammes d'accords",
    english: "Chord diagrams",
    spanish: "Diagramas de acordes",
    german: "Akkorddiagramme",
    chinese_simplified: "和弦图表",
  },
  midi_inputs: {
    french: "Entrées MIDI",
    english: "MIDI inputs",
    spanish: "Entradas MIDI",
    german: "MIDI-Eingänge",
    chinese_simplified: "MIDI 输入",
  },
  sound_preset: {
    french: "Préréglage de sortie",
    english: "Output preset",
    spanish: "Preajuste de salida",
    german: "Ausgangs-Preset",
    chinese_simplified: "输出预设",
  },
  highlight_wrong_notes: {
    french: "Souligner les erreurs",
    english: "Highlight wrong notes",
    spanish: "Resaltar errores",
    german: "Falsche Noten markieren",
    chinese_simplified: "突出显示错误音符",
  },
  highlight_correct_notes: {
    french: "Souligner les réussites",
    english: "Highlight correct notes",
    spanish: "Resaltar aciertos",
    german: "Richtige Noten markieren",
    chinese_simplified: "突出显示正确音符",
  },
  highlight_missed_notes: {
    french: "Souligner les manquements",
    english: "Highlight missed notes",
    spanish: "Resaltar omisiones",
    german: "Verpasste Noten markieren",
    chinese_simplified: "突出显示遗漏音符",
  },
  by: {
    french: "par",
    english: "by",
    spanish: "por",
    german: "von",
    chinese_simplified: "由",
  },
  recents: {
    french: "Récents",
    english: "Recents",
    spanish: "Recientes",
    german: "Kürzlich",
    chinese_simplified: "最近",
  },
  dark: {
    french: "Sombre",
    english: "Dark",
    spanish: "Oscuro",
    german: "Dunkel",
    chinese_simplified: "深色",
  },
  light: {
    french: "Clair",
    english: "Light",
    spanish: "Claro",
    german: "Hell",
    chinese_simplified: "浅色",
  },
  your_playlists: {
    french: "Vos playlists",
    english: "Your playlists",
    spanish: "Tus listas",
    german: "Deine Playlists",
    chinese_simplified: "您的播放列表",
  },
  new_playlist: {
    french: "Nouvelle playlist",
    english: "New playlist",
    spanish: "Nueva lista",
    german: "Neue Playlist",
    chinese_simplified: "新建播放列表",
  },
  title: {
    french: "Titre",
    english: "Title",
    spanish: "Título",
    german: "Titel",
    chinese_simplified: "标题",
  },
  enter_the_title: {
    french: "Entrez le titre",
    english: "Enter the title",
    spanish: "Escribe el título",
    german: "Titel eingeben",
    chinese_simplified: "输入标题",
  },
  description: {
    french: "Description",
    english: "Description",
    spanish: "Descripción",
    german: "Beschreibung",
    chinese_simplified: "描述",
  },
  optional: {
    french: "(optionnel)",
    english: "(optional)",
    spanish: "(opcional)",
    german: "(optional)",
    chinese_simplified: "（可选）",
  },
  enter_your_description: {
    french: "Entrez la description...",
    english: "Enter your description...",
    spanish: "Escribe tu descripción...",
    german: "Beschreibung eingeben...",
    chinese_simplified: "输入描述...",
  },
  tags: {
    french: "Tags",
    english: "Tags",
    spanish: "Etiquetas",
    german: "Tags",
    chinese_simplified: "标签",
  },
  max: {
    french: "max",
    english: "max",
    spanish: "máx.",
    german: "max",
    chinese_simplified: "最大",
  },
  submit: {
    french: "Soumettre",
    english: "Submit",
    spanish: "Enviar",
    german: "Senden",
    chinese_simplified: "提交",
  },
  save: {
    french: "Enregistrer",
    english: "Save",
    spanish: "Guardar",
    german: "Speichern",
    chinese_simplified: "保存",
  },
  exercices: {
    french: "Exercices",
    english: "Exercises",
    spanish: "Ejercicios",
    german: "Übungen",
    chinese_simplified: "练习",
  },
  exercice: {
    french: "Exercice",
    english: "Exercise",
    spanish: "Ejercicio",
    german: "Übung",
    chinese_simplified: "练习",
  },
  medium: {
    french: "médium",
    english: "medium",
    spanish: "medio",
    german: "mittel",
    chinese_simplified: "中",
  },
  original: {
    french: "Original",
    english: "Original",
    spanish: "Original",
    german: "Original",
    chinese_simplified: "原始",
  },
  styles: {
    french: "Styles",
    english: "Styles",
    spanish: "Estilos",
    german: "Stile",
    chinese_simplified: "风格",
  },
  sounds: {
    french: "Sons",
    english: "Sounds",
    spanish: "Sonidos",
    german: "Sounds",
    chinese_simplified: "音效",
  },
} as const;
