export const availableLanguages = ["fr", "en", "es", "de", "zh"] as const;

export const languagePack = {
  homepageDefaultTitle: {
    fr: "Bienvenue sur Music Sandbox !",
    en: "Welcome to Music Sandbox!",
    es: "¡Bienvenido a Music Sandbox!",
    de: "Willkommen bei Music Sandbox!",
    zh: "欢迎来到 Music Sandbox！",
  },
  homepageSessionTitle: {
    fr: "Bon retour parmi nous",
    en: "Welcome back",
    es: "Bienvenido de nuevo",
    de: "Willkommen zurück",
    zh: "欢迎回来",
  },
  homepage: {
    fr: "Page d'Accueil",
    en: "Home Page",
    es: "Página de Inicio",
    de: "Startseite",
    zh: "主页",
  },
  dashboard: {
    fr: "Tableau de bord",
    en: "Dashboard",
    es: "Panel de control",
    de: "Dashboard",
    zh: "仪表板",
  },
  explorePageTitle: {
    fr: "Explorer",
    en: "Explore",
    es: "Explorar",
    de: "Entdecken",
    zh: "浏览",
  },
  favoritesPageTitle: {
    fr: "Favoris",
    en: "Favorites",
    es: "Favoritos",
    de: "Favoriten",
    zh: "收藏",
  },
  dashboardPageTitle: {
    fr: "Vos playlists",
    en: "Your playlists",
    es: "Tus listas",
    de: "Deine Playlists",
    zh: "您的播放列表",
  },
  recentlyPlayed: {
    fr: "Joués récemment",
    en: "Recently played",
    es: "Recientes",
    de: "Zuletzt gespielt",
    zh: "最近播放",
  },
  moreOfThem: {
    fr: "Vous les avez aimé",
    en: "You liked them",
    es: "Te gustaron",
    de: "Dir haben sie gefallen",
    zh: "你喜欢的",
  },
  popularExercices: {
    fr: "Exercices populaires",
    en: "Popular exercises",
    es: "Ejercicios populares",
    de: "Beliebte Übungen",
    zh: "热门练习",
  },
  discover: {
    fr: "Découvrir",
    en: "Discover",
    es: "Descubrir",
    de: "Entdecken",
    zh: "发现",
  },
  accounts: {
    fr: "Utilisateurs",
    en: "Users",
    es: "Usuarios",
    de: "Benutzer",
    zh: "用户",
  },
  playlists: {
    fr: "Playlists",
    en: "Playlists",
    es: "Listas",
    de: "Playlists",
    zh: "播放列表",
  },
  general: {
    fr: "Général",
    en: "General",
    es: "General",
    de: "Allgemein",
    zh: "常规",
  },
  backing_track: {
    fr: "Accompagnement",
    en: "Backing track",
    es: "Acompañamiento",
    de: "Begleitung",
    zh: "伴奏",
  },
  appearance: {
    fr: "Apparence",
    en: "Appearance",
    es: "Apariencia",
    de: "Aussehen",
    zh: "外观",
  },
  midi: {
    fr: "MIDI",
    en: "MIDI",
    es: "MIDI",
    de: "MIDI",
    zh: "MIDI",
  },
  seeAll: {
    fr: "voir tout",
    en: "see all",
    es: "ver todo",
    de: "alle anzeigen",
    zh: "查看全部",
  },
  profile: {
    fr: "Profil",
    en: "Profile",
    es: "Perfil",
    de: "Profil",
    zh: "个人资料",
  },
  settings: {
    fr: "Paramètres",
    en: "Settings",
    es: "Ajustes",
    de: "Einstellungen",
    zh: "设置",
  },
  theme: {
    fr: "Thème",
    en: "Theme",
    es: "Tema",
    de: "Theme",
    zh: "主题",
  },
  language: {
    fr: "Langue",
    en: "Language",
    es: "Idioma",
    de: "Sprache",
    zh: "语言",
  },
  log_out: {
    fr: "Déconnexion",
    en: "Log out",
    es: "Cerrar sesión",
    de: "Abmelden",
    zh: "登出",
  },
  overview: {
    fr: "Aperçu",
    en: "Overview",
    es: "Resumen",
    de: "Übersicht",
    zh: "概览",
  },
  liked: {
    fr: "Aimés",
    en: "Liked",
    es: "Me gusta",
    de: "Gefällt mir",
    zh: "喜欢",
  },
  users: {
    fr: "Utilisateurs",
    en: "Users",
    es: "Usuarios",
    de: "Benutzer",
    zh: "用户",
  },
  user: {
    fr: "Utilisateur",
    en: "User",
    es: "Usuario",
    de: "Benutzer",
    zh: "用户",
  },
  bpm: {
    fr: "BPM",
    en: "BPM",
    es: "BPM",
    de: "BPM",
    zh: "BPM",
  },
  pop: {
    fr: "Pop.", // popularité
    en: "Pop.",
    es: "Pop.",
    de: "Pop.",
    zh: "热度",
  },
  all: {
    fr: "Tous",
    en: "All",
    es: "Todos",
    de: "Alle",
    zh: "全部",
  },
  browse_exercices: {
    fr: "Parcourir les exercices",
    en: "Browse exercises",
    es: "Explorar ejercicios",
    de: "Übungen durchsuchen",
    zh: "浏览练习",
  },
  search_in_playlist: {
    fr: "Chercher dans la playlist",
    en: "Search in playlist",
    es: "Buscar en la lista",
    de: "In Playlist suchen",
    zh: "在播放列表中搜索",
  },
  piano_roll: {
    fr: "Piano",
    en: "Piano",
    es: "Piano",
    de: "Klavier",
    zh: "钢琴",
  },
  chords: {
    fr: "Accords",
    en: "Chords",
    es: "Acordes",
    de: "Akkorde",
    zh: "和弦",
  },
  sheet: {
    fr: "Partition",
    en: "Sheet",
    es: "Partitura",
    de: "Notenblatt",
    zh: "乐谱",
  },
  guitar: {
    fr: "Guitare",
    en: "Guitar",
    es: "Guitarra",
    de: "Gitarre",
    zh: "吉他",
  },
  save_settings: {
    fr: "Enregistrer les paramètres",
    en: "Save settings",
    es: "Guardar ajustes",
    de: "Einstellungen speichern",
    zh: "保存设置",
  },
  default: {
    fr: "Défaut",
    en: "Default",
    es: "Predeterminado",
    de: "Standard",
    zh: "默认",
  },
  presets: {
    fr: "préréglages",
    en: "presets",
    es: "ajustes previos",
    de: "Voreinstellungen",
    zh: "预设",
  },
  count_before_play: {
    fr: "Décompte",
    en: "Count-in",
    es: "Cuenta atrás",
    de: "Einzählen",
    zh: "预拍",
  },
  transpose: {
    fr: "Transposition",
    en: "Transpose",
    es: "Transposición",
    de: "Transponieren",
    zh: "移调",
  },
  practice: {
    fr: "Pratique",
    en: "Practice",
    es: "Práctica",
    de: "Üben",
    zh: "练习",
  },
  repeats: {
    fr: "Répétitions",
    en: "Repeats",
    es: "Repeticiones",
    de: "Wiederholungen",
    zh: "重复",
  },
  bpm_practice: {
    fr: "Pratique BPM",
    en: "BPM practice",
    es: "Práctica BPM",
    de: "BPM-Übung",
    zh: "BPM 练习",
  },
  active: {
    fr: "Activé",
    en: "Active",
    es: "Activado",
    de: "Aktiviert",
    zh: "已激活",
  },
  melody: {
    fr: "Mélodie",
    en: "Melody",
    es: "Melodía",
    de: "Melodie",
    zh: "旋律",
  },
  piano: {
    fr: "Piano",
    en: "Piano",
    es: "Piano",
    de: "Klavier",
    zh: "钢琴",
  },
  bass: {
    fr: "Basse",
    en: "Bass",
    es: "Bajo",
    de: "Bass",
    zh: "贝斯",
  },
  drums: {
    fr: "Batterie",
    en: "Drums",
    es: "Batería",
    de: "Schlagzeug",
    zh: "鼓",
  },
  style: {
    fr: "Style",
    en: "Style",
    es: "Estilo",
    de: "Stil",
    zh: "风格",
  },
  show_chords: {
    fr: "Afficher les accords",
    en: "Show chords",
    es: "Mostrar acordes",
    de: "Akkorde anzeigen",
    zh: "显示和弦",
  },
  highlight_current_measure: {
    fr: "Souligner la mesure actuelle",
    en: "Highlight current measure",
    es: "Resaltar compás actual",
    de: "Aktuellen Takt markieren",
    zh: "突出显示当前小节",
  },
  chords_diagrams: {
    fr: "Diagrammes d'accords",
    en: "Chord diagrams",
    es: "Diagramas de acordes",
    de: "Akkorddiagramme",
    zh: "和弦图表",
  },
  midi_inputs: {
    fr: "Entrées MIDI",
    en: "MIDI inputs",
    es: "Entradas MIDI",
    de: "MIDI-Eingänge",
    zh: "MIDI 输入",
  },
  sound_preset: {
    fr: "Préréglage de sortie",
    en: "Output preset",
    es: "Preajuste de salida",
    de: "Ausgangs-Preset",
    zh: "输出预设",
  },
  highlight_wrong_notes: {
    fr: "Souligner les erreurs",
    en: "Highlight wrong notes",
    es: "Resaltar errores",
    de: "Falsche Noten markieren",
    zh: "突出显示错误音符",
  },
  highlight_correct_notes: {
    fr: "Souligner les réussites",
    en: "Highlight correct notes",
    es: "Resaltar aciertos",
    de: "Richtige Noten markieren",
    zh: "突出显示正确音符",
  },
  highlight_missed_notes: {
    fr: "Souligner les manquements",
    en: "Highlight missed notes",
    es: "Resaltar omisiones",
    de: "Verpasste Noten markieren",
    zh: "突出显示遗漏音符",
  },
  by: {
    fr: "par",
    en: "by",
    es: "por",
    de: "von",
    zh: "由",
  },
  recents: {
    fr: "Récents",
    en: "Recents",
    es: "Recientes",
    de: "Kürzlich",
    zh: "最近",
  },
  dark: {
    fr: "Sombre",
    en: "Dark",
    es: "Oscuro",
    de: "Dunkel",
    zh: "深色",
  },
  light: {
    fr: "Clair",
    en: "Light",
    es: "Claro",
    de: "Hell",
    zh: "浅色",
  },
  your_playlists: {
    fr: "Vos playlists",
    en: "Your playlists",
    es: "Tus listas",
    de: "Deine Playlists",
    zh: "您的播放列表",
  },
  new_playlist: {
    fr: "Nouvelle playlist",
    en: "New playlist",
    es: "Nueva lista",
    de: "Neue Playlist",
    zh: "新建播放列表",
  },
  title: {
    fr: "Titre",
    en: "Title",
    es: "Título",
    de: "Titel",
    zh: "标题",
  },
  enter_the_title: {
    fr: "Entrez le titre",
    en: "Enter the title",
    es: "Escribe el título",
    de: "Titel eingeben",
    zh: "输入标题",
  },
  description: {
    fr: "Description",
    en: "Description",
    es: "Descripción",
    de: "Beschreibung",
    zh: "描述",
  },
  optional: {
    fr: "(optionnel)",
    en: "(optional)",
    es: "(opcional)",
    de: "(optional)",
    zh: "（可选）",
  },
  enter_your_description: {
    fr: "Entrez la description...",
    en: "Enter your description...",
    es: "Escribe tu descripción...",
    de: "Beschreibung eingeben...",
    zh: "输入描述...",
  },
  tags: {
    fr: "Tags",
    en: "Tags",
    es: "Etiquetas",
    de: "Tags",
    zh: "标签",
  },
  max: {
    fr: "max",
    en: "max",
    es: "máx.",
    de: "max",
    zh: "最大",
  },
  submit: {
    fr: "Soumettre",
    en: "Submit",
    es: "Enviar",
    de: "Senden",
    zh: "提交",
  },
  save: {
    fr: "Enregistrer",
    en: "Save",
    es: "Guardar",
    de: "Speichern",
    zh: "保存",
  },
  exercices: {
    fr: "Exercices",
    en: "Exercises",
    es: "Ejercicios",
    de: "Übungen",
    zh: "练习",
  },
  exercice: {
    fr: "Exercice",
    en: "Exercise",
    es: "Ejercicio",
    de: "Übung",
    zh: "练习",
  },
  medium: {
    fr: "médium",
    en: "medium",
    es: "medio",
    de: "mittel",
    zh: "中",
  },
  original: {
    fr: "Original",
    en: "Original",
    es: "Original",
    de: "Original",
    zh: "原始",
  },
  styles: {
    fr: "Styles",
    en: "Styles",
    es: "Estilos",
    de: "Stile",
    zh: "风格",
  },
  sounds: {
    fr: "Sons",
    en: "Sounds",
    es: "Sonidos",
    de: "Sounds",
    zh: "音效",
  },
  login: {
    fr: "Connexion",
    en: "Login",
    es: "Iniciar sesión",
    de: "Anmelden",
    zh: "登录",
  },
  or_login_with: {
    fr: "Ou se connecter avec",
    en: "Or login with",
    es: "O iniciar sesión con",
    de: "Oder anmelden mit",
    zh: "或使用以下方式登录",
  },
  dont_have_an_account: {
    fr: "Pas encore de compte ?",
    en: "Don't have an account ?",
    es: "¿No tienes cuenta ?",
    de: "Noch kein Konto ?",
    zh: "还没有账号？",
  },
  register_here: {
    fr: "s'inscrire ici",
    en: "register here",
    es: "regístrate aquí",
    de: "hier registrieren",
    zh: "在此注册",
  },
  login_to_your_account: {
    fr: "Connectez-vous à votre compte",
    en: "Login to your account",
    es: "Inicia sesión en tu cuenta",
    de: "In dein Konto einloggen",
    zh: "登录您的账号",
  },
  email: {
    fr: "Email",
    en: "Email",
    es: "Correo electrónico",
    de: "E-Mail",
    zh: "电子邮件",
  },
  password: {
    fr: "Mot de passe",
    en: "Password",
    es: "Contraseña",
    de: "Passwort",
    zh: "密码",
  },
  remember_me: {
    fr: "se souvenir de moi",
    en: "remember me",
    es: "recuérdame",
    de: "angemeldet bleiben",
    zh: "记住我",
  },
  forgot_password: {
    fr: "mot de passe oublié ?",
    en: "forgot password ?",
    es: "¿olvidaste tu contraseña ?",
    de: "Passwort vergessen ?",
    zh: "忘记密码？",
  },
  already_have_an_account: {
    fr: "Vous avez déjà un compte ?",
    en: "Already have an account ?",
    es: "¿Ya tienes una cuenta ?",
    de: "Hast du bereits ein Konto ?",
    zh: "已经有账号了？",
  },
  login_here: {
    fr: "se connecter ici",
    en: "login here",
    es: "inicia sesión aquí",
    de: "hier anmelden",
    zh: "在此登录",
  },
  create_your_account: {
    fr: "Créez votre compte",
    en: "Create your account",
    es: "Crea tu cuenta",
    de: "Konto erstellen",
    zh: "创建您的账号",
  },
  username: {
    fr: "Nom d'utilisateur",
    en: "Username",
    es: "Nombre de usuario",
    de: "Benutzername",
    zh: "用户名",
  },
  confirm_password: {
    fr: "Confirmer le mot de passe",
    en: "Confirm password",
    es: "Confirmar contraseña",
    de: "Passwort bestätigen",
    zh: "确认密码",
  },
  by_checking_this: {
    fr: "En cochant ceci, j'accepte tout dans",
    en: "By checking this, i agree all statements in",
    es: "Al marcar esto, acepto todo en",
    de: "Hiermit stimme ich allem zu in",
    zh: "勾选此项即表示我同意",
  },
  therms_of_service: {
    fr: "les conditions d'utilisation",
    en: "terms of service",
    es: "términos de servicio",
    de: "Nutzungsbedingungen",
    zh: "服务条款",
  },
  register: {
    fr: "S'inscrire",
    en: "Register",
    es: "Registrarse",
    de: "Registrieren",
    zh: "注册",
  },
  search: {
    fr: "Rechercher",
    en: "Search",
    es: "Buscar",
    de: "Suchen",
    zh: "搜索",
  },
} as const;
