@startuml

left to right direction
skinparam packageStyle rectangle

actor "Visiteur" as V
actor "Utilisateur connecté" as U

U -|> V

rectangle "Gestion des features" {

  usecase "Rechercher un exercice" as UC1
  usecase "Jouer un exercice" as UC2

  usecase "Liker un utilisateur" as UC3
  usecase "Liker un exercice" as UC4
  usecase "Liker une playlist" as UC5
  usecase "Enregistrer dans les favoris" as UC6

  usecase "Créer une playlist" as UC7
  usecase "Créer un exercice" as UC8
  usecase "Enregistrer dans une playlist" as UC9

  usecase "Configurer un exercice" as UC10
  usecase "Enregistrer sa configuration" as UC11

  V --> UC1
  V --> UC2

  U --> UC3
  U --> UC4
  U --> UC5
  U --> UC7
  U --> UC8
  U --> UC10

  UC3 ..> UC6 : <<include>>
  UC4 ..> UC6 : <<include>>
  UC5 ..> UC6 : <<include>>

  UC8 ..> UC9 : <<include>>

  UC10 ..> UC11 : <<include>>
}

@enduml